### ISSUE TITLE
Fail to parse save file

### ISSUE THREAD

**Issue by nanor88** [reubengann/Witcher3MapViewer#16]
Hi,
I just downloaded your program but it seems it can't parse my save files.
I have the latest version (0.4), the latest version of the game on Steam and .NET 4.8 installed.
My game is in french and have a few mods installed.

Here is the stacktrace:
Description : process stopped due to unmanaged exception
Information : System.Exception
   at Witcher3MapViewer.Witcher3SaveFile.ReadPorpHandle(System.IO.BinaryReader, System.String)
   at Witcher3MapViewer.Witcher3SaveFile.ReadSingleSizeSpec(System.IO.BinaryReader)
   at Witcher3MapViewer.Witcher3SaveFile.ReadPorpHandle(System.IO.BinaryReader, System.String)
   at Witcher3MapViewer.Witcher3SaveFile.ReadWitcher3PORPVariable(System.IO.BinaryReader)
   at Witcher3MapViewer.Witcher3SaveFile.LoadSaveQuick(System.String)
   at Witcher3MapViewer.MainWindow.GetMostRecentSaveFile()
   at Witcher3MapViewer.MainWindow..ctor()

Informations sur l'exception : System.Windows.Markup.XamlParseException
   at System.Windows.Markup.XamlReader.RewrapException(System.Exception, System.Xaml.IXamlLineInfo, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream, System.Windows.Markup.ParserContext)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at Witcher3MapViewer.App.Main()

The failing save file is also attached.
[QuickSave_1263fa_7e534800_4eceb.zip](https://github.com/reubengann/Witcher3MapViewer/files/6849059/QuickSave_1263fa_7e534800_4eceb.zip)

Thank you !

**Comment by reubengann** [comment]
Thanks for the report. I will have a look.

**Comment by nanor88** [comment]
Thank you
Also it's probably unrelated but in manual mode I can't even check quests, although I can do everything else normally.
I tried on both x64 and x86 versions.
